---
title: "Lab sessions: Day 1"
author: "Rob J Hyndman"
date: "26 September 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, cache=TRUE, messages=FALSE, warnings=FALSE)
library(fpp2)
```

# Lab Session 1

```{r}
retaildata <- readxl::read_excel("retail.xlsx", skip = 1)
mytimeseries <- ts(retaildata[["A3349873A"]],
                  frequency=12, start=c(1982,4))
autoplot(mytimeseries)
```

# Lab Session 2

```{r lab2}
ggseasonplot(mytimeseries)
ggsubseriesplot(mytimeseries)
ggAcf(mytimeseries)
```

```{r acf}
ggAcf(mytimeseries, plot=FALSE)
```

# Lab Session 3

```{r snaive}
fc <- snaive(mytimeseries, h=36)
autoplot(fc)
checkresiduals(fc)
```

# Lab Session 4

```{r}
x1 <- window(mytimeseries, end=c(2010,12))
x2 <- window(mytimeseries, start=2011)
autoplot(cbind(Training=x1,Test=x2))
f1 <- snaive(x1, h=length(x2))
autoplot(f1) + autolayer(x2)
accuracy(f1,x2)
checkresiduals(f1)
```

# Lab Session 5


```{r}
fit <- stl(bricksq, s.window=11)
autoplot(fit)
```

```{r}
sa <- seasadj(fit)
autoplot(sa)
sa %>% naive %>% autoplot
fc <- stlf(bricksq, s.window=11, method='naive')
autoplot(fc)
checkresiduals(fc)
fc2 <- stlf(bricksq, s.window=11, method='naive', robust=TRUE)
autoplot(fc2)
checkresiduals(fc2)
```

# Lab Session 6

```{r}
fc1 <- ses(eggs, h=100)
fc2 <- holt(eggs, h=100)
fc3 <- holt(eggs, damped=TRUE, h=100)
accuracy(fc1)
accuracy(fc2)
accuracy(fc3)
checkresiduals(fc2)
```

# Lab Session 7

```{r}
fc <- hw(mytimeseries, seasonal='mult')
fc2 <- hw(mytimeseries,seasonal='mult', damped=TRUE)
accuracy(fc)
accuracy(fc2)
checkresiduals(fc)
```

```{r}
f2 <- hw(x1)
accuracy(f1,x2)
accuracy(f2,x2)
```

