---
title: "Lab sessions: Day 2"
author: "Rob J Hyndman"
date: "27 September 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, cache=TRUE, messages=FALSE, warnings=FALSE)
library(fpp2)
```

# Lab Session 8

```{r}
retaildata <- readxl::read_excel("retail.xlsx", skip = 1)
mytimeseries <- ts(retaildata[["A3349873A"]],
                  frequency=12, start=c(1982,4))
fit <- ets(mytimeseries)
summary(fit)
autoplot(forecast(fit))

x1 <- window(mytimeseries, end=c(2010,12))
x2 <- window(mytimeseries, start=2011)
f1 <- snaive(x1, h=length(x2))
f2 <- hw(x1, h=length(x2), seasonal='multi')
f3 <- forecast(ets(x1), h=length(x2))
accuracy(f1,x2)
accuracy(f2,x2)
accuracy(f3,x2)
```

```{r}
bicoal %>% ets %>% forecast %>% autoplot
chicken %>% ets %>% forecast %>% autoplot
dole %>% ets %>% forecast %>% autoplot
usdeaths %>% ets %>% forecast %>% autoplot
bricksq %>% ets %>% forecast %>% autoplot
lynx %>% ets %>% forecast %>% autoplot
ibmclose %>% ets %>% forecast %>% autoplot
eggs %>% ets %>% forecast %>% autoplot
ausbeer %>% ets %>% forecast %>% autoplot
```

# Lab Session 9

```{r}
autoplot(usnetelec)
```

No transformation required

```{r}
autoplot(mcopper)
(lambda <- BoxCox.lambda(mcopper))
mcopper %>% BoxCox(lambda=lambda) %>% autoplot
```

```{r}
autoplot(enplanements)
(lambda <- BoxCox.lambda(enplanements))
# I don't like such strong transformations. Will use 0 instead
enplanements %>% BoxCox(lambda=0) %>% autoplot
```

```{r}
autoplot(a10)
(lambda <- BoxCox.lambda(a10))
a10 %>% BoxCox(lambda=lambda) %>% autoplot
```

```{r}
autoplot(cangas)
```

```{r}
(lambda <- BoxCox.lambda(mytimeseries))
mytimeseries %>% BoxCox(lambda=lambda) %>% autoplot
```

```{r}
f4 <- stlf(x1, lambda=lambda, h=length(x2))
accuracy(f4,x2)
autoplot(f4) + autolayer(x2, series="Test data")
```

# Lab Session 10

```{r}
usnetelec %>% autoplot
usnetelec %>% diff %>% autoplot
```

```{r}
usgdp %>% autoplot
usgdp %>% diff %>% autoplot
```

```{r}
lambda <- BoxCox.lambda(mcopper)
mcopper %>% BoxCox(lambda=lambda) %>% autoplot
mcopper %>% BoxCox(lambda=lambda) %>% diff(lag=12) %>% autoplot
```

```{r}
enplanements %>% log %>% autoplot
enplanements %>% log %>% diff(lag=12) %>% autoplot
enplanements %>% log %>% diff(lag=12) %>% diff %>% autoplot
```

```{r}
visitors %>% autoplot
lambda <- BoxCox.lambda(visitors)
visitors %>% BoxCox(lambda=lambda) %>% autoplot
visitors %>% BoxCox(lambda=lambda) %>% diff(lag=12) %>% autoplot
visitors %>% BoxCox(lambda=lambda) %>% diff(lag=12) %>% diff %>% autoplot
```

```{r}
mytimeseries %>% 
  BoxCox(lambda=0.12) %>%
  diff(lag=12) %>%
  diff(lag=1) %>%
  autoplot
```

# Lab Session 11

```{r}
wmurders %>% autoplot
wmurders %>% log %>% autoplot
fit <- auto.arima(wmurders, lambda=0, stepwise=FALSE, approximation=FALSE, max.p=10, max.q=10, max.order=10)
checkresiduals(fit)
forecast(fit) %>% autoplot
wmurders %>% ets %>% forecast %>% autoplot
wmurders %>% ets(lambda=0, model="AAN") %>% forecast %>% autoplot
```

# Lab Session 12


```{r}
lambda <- BoxCox.lambda(mytimeseries)
auto.arima(mytimeseries, lambda=lambda)
(arimamod <- auto.arima(mytimeseries,
              D=1, lambda=lambda,
              stepwise=FALSE,
              approximation=FALSE))
```

```{r}
newretaildata <- readxl::read_excel("8501011.xls", sheet=2, skip=9)
mynewdata <- ts(newretaildata[["A3349873A"]],
                  frequency=12, start=c(1982,4))
mynewdata <- window(mynewdata, start=2014)

lambda <- BoxCox.lambda(mytimeseries)
(etsmod <- ets(mytimeseries))

f1 <- snaive(mytimeseries, h=length(mynewdata))
f2 <- hw(mytimeseries, h=length(mynewdata), seasonal='multi')
f3 <- forecast(etsmod, h=length(mynewdata))
f4 <- stlf(mytimeseries, lambda=lambda, h=length(mynewdata))
f5 <- forecast(arimamod, h=length(mynewdata))
```

```{r}
checkresiduals(f1)
checkresiduals(f2)
checkresiduals(f3)
checkresiduals(f4)
checkresiduals(f5)
```

```{r}
accuracy(f1,mynewdata)["Test set","RMSE"]
accuracy(f2,mynewdata)["Test set","RMSE"]
accuracy(f3,mynewdata)["Test set","RMSE"]
accuracy(f4,mynewdata)["Test set","RMSE"]
accuracy(f5,mynewdata)["Test set","RMSE"]
```

```{r}
autoplot(f5) +
  autolayer(mynewdata, series="New data")
```
