---
title: "Tidy time series & forecasting in R"
slug: workshop2020
aliases:
  - /workshop2020/
author: "Rob J Hyndman"
date: 2020-01-27
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
options(digits = 3, width = 75)
library(tidyverse)
```

## Venue

[**rstudio:conf2020**, San Francisco](https://rstd.io/conf)

## Course description

It is becoming increasingly common for organizations to collect huge amounts of data over time, and existing time series analysis tools are not always suitable to handle the scale, frequency and structure of the data collected. In this workshop, we will look at some new packages and methods that have been developed to handle the analysis of large collections of time series.

On day 1, we will look at the tsibble data structure for flexibly managing collections of related time series. We will look at how to do data wrangling, data visualizations and exploratory data analysis. We will explore feature-based methods to explore time series data in high dimensions. A similar feature-based approach can be used to identify anomalous time series within a collection of time series, or to cluster or classify time series. Primary packages for day 1 will be tsibble, lubridate and feast (along with the tidyverse of course).

Day 2 will be about forecasting. We will look at some classical time series models and how they are automated in the fable package. We will look at creating ensemble forecasts and hybrid forecasts, as well as some new forecasting methods that have performed well in large-scale forecasting competitions. Finally, we will look at forecast reconciliation, allowing millions of time series to be forecast in a relatively short time while accounting for constraints on how the series are related.

## Learning objectives

Attendees will learn:

1. How to wrangle time series data with familiar tidy tools.
2. How to compute time series features and visualize large collections of time series.
3. How to select a good forecasting algorithm for your time series.
4. How to ensure forecasts of a large collection of time series are coherent.

## Is this course for me?

This course will be appropriate for you if you answer yes to these questions:

1. Do you already use the tidyverse packages in R such as dplyr, tidyr, tibble and ggplot2?
2. Do you need to analyse large collections of related time series?
3. Would you like to learn how to use some new tidy tools for time series analysis including visualization, decomposition and forecasting?

## Prework

Participants should be familiar with the use of R, at least to the point where they can fit a linear regression model, and work with data frames.

Please bring your own laptop with a recent version of R and RStudio installed. The following code will install the main packages needed for the workshop.

```r
install.packages("tidyverse", dependencies=TRUE)
install.packages("fpp3", dependencies=TRUE)
```

## Schedule

| Time          | Activity         |
| :------------ | :--------------- |
| 09:00 - 10:30 | Session 1        |
| 10:30 - 11:00 | *Coffee break*   |
| 11:00 - 12:30 | Session 2        |
| 12:30 - 13:30 | *Lunch break*    |
| 13:30 - 15:00 | Session 3        |
| 15:00 - 15:30 | *Coffee break*   |
| 15:30 - 17:00 | Session 4        |


## Slides


### Day 1

  0. [Background](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/0-intro.pdf)
  1. [Introduction to tsibbles](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/1-tsibbles.pdf)
  2. [Time series graphics](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/2-graphics.pdf)
  3. [Transformations](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/3-transformations.pdf)
  4. [Seasonality and trends](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/4-decompositions.pdf)
  5. [Time series features](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/5-feasts.pdf)

### Day 2

  6. [Introduction to forecasting](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/6-fable.pdf)
  7. [Exponential smoothing](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/7-ets.pdf)
  8. [ARIMA models](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/8-arima.pdf)
  9. [Dynamic regression](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/9-dynamic-regression.pdf)
  10. [Hierarchical forecasting](https://github.com/rstudio-conf-2020/time-series-forecasting/raw/master/materials/10-reconciliation.pdf)

## Lab Sessions

### Lab Session 1

 * Download [`tourism.xlsx`](http://robjhyndman.com/data/tourism.xlsx) from [`http://robjhyndman.com/data/tourism.xlsx`](http://robjhyndman.com/data/tourism.xlsx), and read it into R using `read_excel()` from the `readxl` package.
 * Create a tsibble which is identical to the `tourism` tsibble from the `tsibble` package.
 * Find what combination of `Region` and `Purpose` had the maximum number of overnight trips on average.
 * Create a new tsibble which combines the Purposes and Regions, and just has total trips by State.


### Lab Session 2

- Create time plots of the following time series: `Beer` from `aus_production`, `Lynx` from `pelt`, `Close` from `gafa_stock`
- Use `help()` to find out about the data in each series.
- For the last plot, modify the axis labels and title.

### Lab Session 3

Look at the quarterly tourism data for the Snowy Mountains

   ```r
   snowy <- filter(tourism, Region == "Snowy Mountains")
   ```

  - Use `autoplot()`, `gg_season()` and `gg_subseries()` to explore the data.
  - What do you learn?

### Lab Session 4

Repeat the decomposition using

   ```r
   holidays %>%
     STL(Trips ~ season(window=7) + trend(window=11)) %>%
     autoplot()
  ```

What happens as you change `season(window = ???)` and `trend(window = ???)`?

### Lab Session 5

 * Use ``GGally::ggpairs()`` to look at the relationships between the STL-based features. You might wish to change `seasonal_peak_year` and `seasonal_trough_year` to factors.
 * Which is the peak quarter for holidays in each state?


### Lab Session 6

* Use a feature-based approach to look for outlying series in `PBS`.
* What is unusual about these series?


### Lab Session 7

Find an ETS model for the Gas data from `aus_production`.

  * Why is multiplicative seasonality necessary here?
  * Experiment with making the trend damped.

### Lab Session 8

For the United States GDP data (from `global_economy`):

 * Fit a suitable ARIMA model for the logged data.
 * Produce forecasts of your fitted model. Do the forecasts look reasonable?

### Lab Session 9

For the Australian tourism data (from `tourism`):

 * Fit a suitable ARIMA model for all data.
 * Produce forecasts of your fitted models.
 * Check the forecasts for the "Snowy Mountains" and "Melbourne" regions. Do they look reasonable?

### Lab Session 10

* Prepare aggregations of the PBS data by Concession, Type, and ATC1.
* Use forecast reconciliation with the PBS data, using ETS, ARIMA and SNAIVE models, applied to all but the last 3 years of data.
* Which type of model works best?
* Does the reconciliation improve the forecast accuracy?
* Why doesn't the reconcililation make any difference to the SNAIVE forecasts?

